# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.3.0
_src_path: gh:LCOGT/k8s-application-copier-template
app_description: ' Software for use in astronomical commissioning of instruments on
    the LCOGT network'
app_name: lcogt-commissioning
build_container_on_every_push: true
default_branch_bypass_branch_protection_rules: true
default_branch_name: master
delete_branches_on_merge: true
dockerfile_path: Dockerfile
have_deploy_repo: false
